#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
claude_md="${repo_root}/CLAUDE.md"
default_agents_md="${repo_root}/AGENTS.md"
agents_md="${1:-${default_agents_md}}"

if [[ ! -f "${claude_md}" ]]; then
  echo "Missing ${claude_md}" >&2
  exit 1
fi

python3 - <<'PY' "${claude_md}" "${agents_md}"
from pathlib import Path
import sys

claude_path = Path(sys.argv[1])
agents_path = Path(sys.argv[2])

text = claude_path.read_text()

old_intro = "This file provides guidance to Claude Code (claude.ai/code), Codex when working with code in this repository."
new_intro = "This file provides guidance to AI coding agents working with code in this repository."

# Strip optional leading lines (e.g. bold meta-note) before the H1
if not text.startswith("# CLAUDE.md\n"):
    idx = text.find("\n# CLAUDE.md\n")
    if idx == -1:
        raise SystemExit("CLAUDE.md has an unexpected header format")
    text = text[idx + 1:]  # drop everything before the H1

if old_intro not in text:
    raise SystemExit("CLAUDE.md has an unexpected intro format")

generated = text.replace("# CLAUDE.md", "# AGENTS.md", 1).replace(old_intro, new_intro, 1)
generated = generated.replace(
    "# AGENTS.md\n\n",
    "# AGENTS.md\n\nGenerated from `CLAUDE.md`. Do not edit this file directly.\n\n",
    1,
)

agents_path.write_text(generated)
PY
